remote_theme: nielsenramon/chalk
title: Py Campers
name: Py Campers
ga_analytics: UA-119542427-2
blog_theme: dark
paginate: 25
url: http://pycampers.com/
social:
    github: https://github.com/pycampers
    twitter: https://twitter.com/pycampers
    youtube: https://www.youtube.com/channel/UCgCeAEPuLidDCKJKMZO2eGA
    email: pycampers@gmail.com
